const CATEGORIES = {
    soup: { name: "Sopa", icon: "MEAL_SOUP" },
    salad: { name: "Ensalada", icon: "MEAL_SALAD" },
    omelette: { name: "Tortilla", icon: "MEAL_OMELETTE" },
    pie: { name: "Pastel", icon: "MEAL_PIE" },
    stew: { name: "Guiso", icon: "MEAL_STEW" },
    sandwich: { name: "Bocadillo", icon: "MEAL_SANDWICH" },
    roast: { name: "Asado", icon: "MEAL_ROAST" }
};

function getItemImageUrl(itemId, enchant = 0) {
    if (enchant > 0) return `https://render.albiononline.com/v1/item/${itemId}@${enchant}.png?size=64`;
    return `https://render.albiononline.com/v1/item/${itemId}.png?size=64`;
}

const RECIPES = [

{id:"carrot_soup",name:"Carrot Soup",nameEs:"Sopa de Zanahoria",category:"soup",tier:1,itemId:"T1_MEAL_SOUP",effect:"Regeneracion de Salud +100%",ingredients:{0:[{name:"Carrots",id:"T1_FARM_CARROT",qty:16}],1:[{name:"Carrots",id:"T1_FARM_CARROT",qty:16},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:4}],2:[{name:"Carrots",id:"T1_FARM_CARROT",qty:16},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:4}],3:[{name:"Carrots",id:"T1_FARM_CARROT",qty:16},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:4}]}},
{id:"wheat_soup",name:"Wheat Soup",nameEs:"Sopa de Trigo",category:"soup",tier:3,itemId:"T3_MEAL_SOUP",effect:"Regeneracion de Salud +190%",ingredients:{0:[{name:"Wheat",id:"T3_FARM_WHEAT",qty:48}],1:[{name:"Wheat",id:"T3_FARM_WHEAT",qty:48},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:10}],2:[{name:"Wheat",id:"T3_FARM_WHEAT",qty:48},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:10}],3:[{name:"Wheat",id:"T3_FARM_WHEAT",qty:48},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:10}]}},
{id:"cabbage_soup",name:"Cabbage Soup",nameEs:"Sopa de Col",category:"soup",tier:5,itemId:"T5_MEAL_SOUP",effect:"Regeneracion de Salud +270%",ingredients:{0:[{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:144}],1:[{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:144},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:90}],2:[{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:144},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:90}],3:[{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:144},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:90}]}},
{id:"bean_salad",name:"Bean Salad",nameEs:"Ensalada de Judias",category:"salad",tier:2,itemId:"T2_MEAL_SALAD",effect:"Velocidad de Crafteo +49, Calidad +49",ingredients:{0:[{name:"Beans",id:"T2_FARM_BEANS",qty:8},{name:"Carrots",id:"T1_FARM_CARROT",qty:8}],1:[{name:"Beans",id:"T2_FARM_BEANS",qty:8},{name:"Carrots",id:"T1_FARM_CARROT",qty:8},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:10}],2:[{name:"Beans",id:"T2_FARM_BEANS",qty:8},{name:"Carrots",id:"T1_FARM_CARROT",qty:8},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:10}],3:[{name:"Beans",id:"T2_FARM_BEANS",qty:8},{name:"Carrots",id:"T1_FARM_CARROT",qty:8},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:10}]}},
{id:"turnip_salad",name:"Turnip Salad",nameEs:"Ensalada de Nabo",category:"salad",tier:4,itemId:"T4_MEAL_SALAD",effect:"Velocidad de Crafteo +66, Calidad +66",ingredients:{0:[{name:"Turnips",id:"T4_FARM_TURNIP",qty:24},{name:"Wheat",id:"T3_FARM_WHEAT",qty:24}],1:[{name:"Turnips",id:"T4_FARM_TURNIP",qty:24},{name:"Wheat",id:"T3_FARM_WHEAT",qty:24},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:30}],2:[{name:"Turnips",id:"T4_FARM_TURNIP",qty:24},{name:"Wheat",id:"T3_FARM_WHEAT",qty:24},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:30}],3:[{name:"Turnips",id:"T4_FARM_TURNIP",qty:24},{name:"Wheat",id:"T3_FARM_WHEAT",qty:24},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:30}]}},
{id:"potato_salad",name:"Potato Salad",nameEs:"Ensalada de Patata",category:"salad",tier:6,itemId:"T6_MEAL_SALAD",effect:"Velocidad de Crafteo +100, Calidad +100",ingredients:{0:[{name:"Potatoes",id:"T6_FARM_POTATO",qty:72},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:72}],1:[{name:"Potatoes",id:"T6_FARM_POTATO",qty:72},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:72},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:90}],2:[{name:"Potatoes",id:"T6_FARM_POTATO",qty:72},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:72},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:90}],3:[{name:"Potatoes",id:"T6_FARM_POTATO",qty:72},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:72},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:90}]}},

{id:"chicken_omelette",name:"Chicken Omelette",nameEs:"Tortilla de Pollo",category:"omelette",tier:3,itemId:"T3_MEAL_OMELETTE",effect:"Cast Speed +5%, Cooldown Rate +5%",ingredients:{0:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Wheat",id:"T3_FARM_WHEAT",qty:4},{name:"Hen Eggs",id:"T3_FARM_CHICKEN_EGG",qty:2}],1:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Wheat",id:"T3_FARM_WHEAT",qty:4},{name:"Hen Eggs",id:"T3_FARM_CHICKEN_EGG",qty:2},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:10}],2:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Wheat",id:"T3_FARM_WHEAT",qty:4},{name:"Hen Eggs",id:"T3_FARM_CHICKEN_EGG",qty:2},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:10}],3:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Wheat",id:"T3_FARM_WHEAT",qty:4},{name:"Hen Eggs",id:"T3_FARM_CHICKEN_EGG",qty:2},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:10}]}},
{id:"goose_omelette",name:"Goose Omelette",nameEs:"Tortilla de Ganso",category:"omelette",tier:5,itemId:"T5_MEAL_OMELETTE",effect:"Cast Speed +9.5%, Cooldown Rate +9.5%",ingredients:{0:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:12},{name:"Goose Eggs",id:"T5_FARM_GOOSE_EGG",qty:6}],1:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:12},{name:"Goose Eggs",id:"T5_FARM_GOOSE_EGG",qty:6},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:30}],2:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:12},{name:"Goose Eggs",id:"T5_FARM_GOOSE_EGG",qty:6},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:30}],3:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:12},{name:"Goose Eggs",id:"T5_FARM_GOOSE_EGG",qty:6},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:30}]}},
{id:"pork_omelette",name:"Pork Omelette",nameEs:"Tortilla de Cerdo",category:"omelette",tier:7,itemId:"T7_MEAL_OMELETTE",effect:"Cast Speed +13.5%, Cooldown Rate +13.5%",ingredients:{0:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Goose Eggs",id:"T5_FARM_GOOSE_EGG",qty:18}],1:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Goose Eggs",id:"T5_FARM_GOOSE_EGG",qty:18},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:90}],2:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Goose Eggs",id:"T5_FARM_GOOSE_EGG",qty:18},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:90}],3:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Goose Eggs",id:"T5_FARM_GOOSE_EGG",qty:18},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:90}]}},
{id:"chicken_pie",name:"Chicken Pie",nameEs:"Pastel de Pollo",category:"pie",tier:3,itemId:"T3_MEAL_PIE",effect:"Gathering Yield +5%, Max Load +10%",ingredients:{0:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Flour",id:"T3_MEAL_FLOUR",qty:4},{name:"Wheat",id:"T3_FARM_WHEAT",qty:2}],1:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Flour",id:"T3_MEAL_FLOUR",qty:4},{name:"Wheat",id:"T3_FARM_WHEAT",qty:2},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:10}],2:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Flour",id:"T3_MEAL_FLOUR",qty:4},{name:"Wheat",id:"T3_FARM_WHEAT",qty:2},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:10}],3:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Flour",id:"T3_MEAL_FLOUR",qty:4},{name:"Wheat",id:"T3_FARM_WHEAT",qty:2},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:10}]}},
{id:"goose_pie",name:"Goose Pie",nameEs:"Pastel de Ganso",category:"pie",tier:5,itemId:"T5_MEAL_PIE",effect:"Gathering Yield +10%, Max Load +20%",ingredients:{0:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Flour",id:"T3_MEAL_FLOUR",qty:12},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:6},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:6}],1:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Flour",id:"T3_MEAL_FLOUR",qty:12},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:6},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:6},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:30}],2:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Flour",id:"T3_MEAL_FLOUR",qty:12},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:6},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:6},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:30}],3:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Flour",id:"T3_MEAL_FLOUR",qty:12},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:6},{name:"Cabbage",id:"T5_FARM_CABBAGE",qty:6},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:30}]}},
{id:"pork_pie",name:"Pork Pie",nameEs:"Pastel de Cerdo",category:"pie",tier:7,itemId:"T7_MEAL_PIE",effect:"Gathering Yield +15%, Max Load +30%",ingredients:{0:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Flour",id:"T3_MEAL_FLOUR",qty:36},{name:"Sheep's Milk",id:"T6_FARM_SHEEP_MILK",qty:18},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:18}],1:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Flour",id:"T3_MEAL_FLOUR",qty:36},{name:"Sheep's Milk",id:"T6_FARM_SHEEP_MILK",qty:18},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:18},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:90}],2:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Flour",id:"T3_MEAL_FLOUR",qty:36},{name:"Sheep's Milk",id:"T6_FARM_SHEEP_MILK",qty:18},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:18},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:90}],3:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Flour",id:"T3_MEAL_FLOUR",qty:36},{name:"Sheep's Milk",id:"T6_FARM_SHEEP_MILK",qty:18},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:18},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:90}]}},

{id:"goat_stew",name:"Goat Stew",nameEs:"Guiso de Cabra",category:"stew",tier:4,itemId:"T4_MEAL_STEW",effect:"Damage +5%",ingredients:{0:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Bread",id:"T4_MEAL_BREAD",qty:4},{name:"Turnips",id:"T4_FARM_TURNIP",qty:4}],1:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Bread",id:"T4_MEAL_BREAD",qty:4},{name:"Turnips",id:"T4_FARM_TURNIP",qty:4},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:10}],2:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Bread",id:"T4_MEAL_BREAD",qty:4},{name:"Turnips",id:"T4_FARM_TURNIP",qty:4},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:10}],3:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Bread",id:"T4_MEAL_BREAD",qty:4},{name:"Turnips",id:"T4_FARM_TURNIP",qty:4},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:10}]}},
{id:"mutton_stew",name:"Mutton Stew",nameEs:"Guiso de Cordero",category:"stew",tier:6,itemId:"T6_MEAL_STEW",effect:"Damage +9.5%",ingredients:{0:[{name:"Raw Mutton",id:"T6_MEAL_MEAT",qty:24},{name:"Bread",id:"T4_MEAL_BREAD",qty:12},{name:"Potatoes",id:"T6_FARM_POTATO",qty:12}],1:[{name:"Raw Mutton",id:"T6_MEAL_MEAT",qty:24},{name:"Bread",id:"T4_MEAL_BREAD",qty:12},{name:"Potatoes",id:"T6_FARM_POTATO",qty:12},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:30}],2:[{name:"Raw Mutton",id:"T6_MEAL_MEAT",qty:24},{name:"Bread",id:"T4_MEAL_BREAD",qty:12},{name:"Potatoes",id:"T6_FARM_POTATO",qty:12},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:30}],3:[{name:"Raw Mutton",id:"T6_MEAL_MEAT",qty:24},{name:"Bread",id:"T4_MEAL_BREAD",qty:12},{name:"Potatoes",id:"T6_FARM_POTATO",qty:12},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:30}]}},
{id:"beef_stew",name:"Beef Stew",nameEs:"Guiso de Ternera",category:"stew",tier:8,itemId:"T8_MEAL_STEW",effect:"Damage +13.5%",ingredients:{0:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bread",id:"T4_MEAL_BREAD",qty:36},{name:"Pumpkin",id:"T8_FARM_PUMPKIN",qty:36}],1:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bread",id:"T4_MEAL_BREAD",qty:36},{name:"Pumpkin",id:"T8_FARM_PUMPKIN",qty:36},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:90}],2:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bread",id:"T4_MEAL_BREAD",qty:36},{name:"Pumpkin",id:"T8_FARM_PUMPKIN",qty:36},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:90}],3:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bread",id:"T4_MEAL_BREAD",qty:36},{name:"Pumpkin",id:"T8_FARM_PUMPKIN",qty:36},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:90}]}},
{id:"goat_sandwich",name:"Goat Sandwich",nameEs:"Bocadillo de Cabra",category:"sandwich",tier:4,itemId:"T4_MEAL_SANDWICH",effect:"Max Health +5%",ingredients:{0:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Bread",id:"T4_MEAL_BREAD",qty:4},{name:"Goat's Butter",id:"T4_FARM_GOAT_BUTTER",qty:2}],1:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Bread",id:"T4_MEAL_BREAD",qty:4},{name:"Goat's Butter",id:"T4_FARM_GOAT_BUTTER",qty:2},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:10}],2:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Bread",id:"T4_MEAL_BREAD",qty:4},{name:"Goat's Butter",id:"T4_FARM_GOAT_BUTTER",qty:2},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:10}],3:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Bread",id:"T4_MEAL_BREAD",qty:4},{name:"Goat's Butter",id:"T4_FARM_GOAT_BUTTER",qty:2},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:10}]}},
{id:"mutton_sandwich",name:"Mutton Sandwich",nameEs:"Bocadillo de Cordero",category:"sandwich",tier:6,itemId:"T6_MEAL_SANDWICH",effect:"Max Health +9.5%",ingredients:{0:[{name:"Raw Mutton",id:"T6_MEAL_MEAT",qty:24},{name:"Bread",id:"T4_MEAL_BREAD",qty:12},{name:"Sheep's Butter",id:"T6_FARM_SHEEP_BUTTER",qty:6}],1:[{name:"Raw Mutton",id:"T6_MEAL_MEAT",qty:24},{name:"Bread",id:"T4_MEAL_BREAD",qty:12},{name:"Sheep's Butter",id:"T6_FARM_SHEEP_BUTTER",qty:6},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:30}],2:[{name:"Raw Mutton",id:"T6_MEAL_MEAT",qty:24},{name:"Bread",id:"T4_MEAL_BREAD",qty:12},{name:"Sheep's Butter",id:"T6_FARM_SHEEP_BUTTER",qty:6},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:30}],3:[{name:"Raw Mutton",id:"T6_MEAL_MEAT",qty:24},{name:"Bread",id:"T4_MEAL_BREAD",qty:12},{name:"Sheep's Butter",id:"T6_FARM_SHEEP_BUTTER",qty:6},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:30}]}},
{id:"beef_sandwich",name:"Beef Sandwich",nameEs:"Bocadillo de Ternera",category:"sandwich",tier:8,itemId:"T8_MEAL_SANDWICH",effect:"Max Health +13.5%",ingredients:{0:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bread",id:"T4_MEAL_BREAD",qty:36},{name:"Cow's Butter",id:"T8_FARM_COW_BUTTER",qty:18}],1:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bread",id:"T4_MEAL_BREAD",qty:36},{name:"Cow's Butter",id:"T8_FARM_COW_BUTTER",qty:18},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:90}],2:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bread",id:"T4_MEAL_BREAD",qty:36},{name:"Cow's Butter",id:"T8_FARM_COW_BUTTER",qty:18},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:90}],3:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bread",id:"T4_MEAL_BREAD",qty:36},{name:"Cow's Butter",id:"T8_FARM_COW_BUTTER",qty:18},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:90}]}},

{id:"roast_chicken",name:"Roast Chicken",nameEs:"Pollo Asado",category:"roast",tier:3,itemId:"T3_MEAL_ROAST",effect:"Lifesteal +3.5%",ingredients:{0:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Beans",id:"T2_FARM_BEANS",qty:4},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:4}],1:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Beans",id:"T2_FARM_BEANS",qty:4},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:4},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:10}],2:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Beans",id:"T2_FARM_BEANS",qty:4},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:4},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:10}],3:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Beans",id:"T2_FARM_BEANS",qty:4},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:4},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:10}]}},
{id:"roast_goose",name:"Roast Goose",nameEs:"Ganso Asado",category:"roast",tier:5,itemId:"T5_MEAL_ROAST",effect:"Lifesteal +6.65%",ingredients:{0:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Turnips",id:"T4_FARM_TURNIP",qty:12},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:12}],1:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Turnips",id:"T4_FARM_TURNIP",qty:12},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:12},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:30}],2:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Turnips",id:"T4_FARM_TURNIP",qty:12},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:12},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:30}],3:[{name:"Raw Goose",id:"T5_MEAL_MEAT",qty:24},{name:"Turnips",id:"T4_FARM_TURNIP",qty:12},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:12},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:30}]}},
{id:"roast_pork",name:"Roast Pork",nameEs:"Cerdo Asado",category:"roast",tier:7,itemId:"T7_MEAL_ROAST",effect:"Lifesteal +9.45%",ingredients:{0:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Cow's Milk",id:"T8_FARM_COW_MILK",qty:18}],1:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Cow's Milk",id:"T8_FARM_COW_MILK",qty:18},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:90}],2:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Cow's Milk",id:"T8_FARM_COW_MILK",qty:18},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:90}],3:[{name:"Raw Pork",id:"T7_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Cow's Milk",id:"T8_FARM_COW_MILK",qty:18},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:90}]}},
{id:"avalonian_goat_stew",name:"Avalonian Goat Stew",nameEs:"Guiso de Cabra Avaloniano",category:"stew",tier:4,itemId:"T4_MEAL_STEW_AVALON",effect:"Damage +3.5%, Cooldown +3.5%",ingredients:{0:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Carrots",id:"T1_FARM_CARROT",qty:4},{name:"Turnips",id:"T4_FARM_TURNIP",qty:4},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:10}],1:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Carrots",id:"T1_FARM_CARROT",qty:4},{name:"Turnips",id:"T4_FARM_TURNIP",qty:4},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:10},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:10}],2:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Carrots",id:"T1_FARM_CARROT",qty:4},{name:"Turnips",id:"T4_FARM_TURNIP",qty:4},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:10},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:10}],3:[{name:"Raw Goat",id:"T4_MEAL_MEAT",qty:8},{name:"Carrots",id:"T1_FARM_CARROT",qty:4},{name:"Turnips",id:"T4_FARM_TURNIP",qty:4},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:10},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:10}]}},
{id:"avalonian_beef_stew",name:"Avalonian Beef Stew",nameEs:"Guiso de Ternera Avaloniano",category:"stew",tier:8,itemId:"T8_MEAL_STEW_AVALON",effect:"Damage +9.5%, Cooldown +9.5%",ingredients:{0:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Pumpkin",id:"T8_FARM_PUMPKIN",qty:36},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:90}],1:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Pumpkin",id:"T8_FARM_PUMPKIN",qty:36},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:90},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:90}],2:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Pumpkin",id:"T8_FARM_PUMPKIN",qty:36},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:90},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:90}],3:[{name:"Raw Beef",id:"T8_MEAL_MEAT",qty:72},{name:"Bundle of Corn",id:"T7_FARM_CORN",qty:36},{name:"Pumpkin",id:"T8_FARM_PUMPKIN",qty:36},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:90},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:90}]}},
{id:"avalonian_chicken_omelette",name:"Avalonian Chicken Omelette",nameEs:"Tortilla de Pollo Avaloniana",category:"omelette",tier:3,itemId:"T3_MEAL_OMELETTE_AVALON",effect:"Cast Speed +3.5%, Cooldown +3.5%",ingredients:{0:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:4},{name:"Hen Eggs",id:"T3_FARM_CHICKEN_EGG",qty:2},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:10}],1:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:4},{name:"Hen Eggs",id:"T3_FARM_CHICKEN_EGG",qty:2},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:10},{name:"Basic Fish Sauce",id:"T3_MEAL_SAUCE",qty:10}],2:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:4},{name:"Hen Eggs",id:"T3_FARM_CHICKEN_EGG",qty:2},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:10},{name:"Fancy Fish Sauce",id:"T5_MEAL_SAUCE",qty:10}],3:[{name:"Raw Chicken",id:"T3_MEAL_MEAT",qty:8},{name:"Goat's Milk",id:"T4_FARM_GOAT_MILK",qty:4},{name:"Hen Eggs",id:"T3_FARM_CHICKEN_EGG",qty:2},{name:"Avalonian Energy",id:"T4_RUNE_AVALON",qty:10},{name:"Special Fish Sauce",id:"T7_MEAL_SAUCE",qty:10}]}},
];
